### ISSUE TITLE
Fix graphiql

### ISSUE THREAD

**Issue by dankolbman** [kids-first/kf-api-study-creator#485]
The `/graphql` endpoint no longer returns the graphiql interface which provides a convenient way of debugging graphql queries.
This interface should be accessible at `http://localhost:5002/graphql`, however, logs say that the bundle is not available. This may be because either 1) an upstream change to graphene-django broke broke something or 2) we are not serving static content from the server.

If we can't get the `graphiql=True` functionality to work natively, we may have to plug in our own HTML response.
https://github.com/kids-first/kf-api-study-creator/blob/master/creator/urls.py#L43-L44

Ideally, we should not have to distribute any static files from our api and instead return an HTML page with external js bundles. We could either plug in a CDN link to graphiql or try a more advanced interface like [explorer](https://github.com/OneGraph/graphiql-explorer)

**Comment by dankolbman** [comment]
Here's the template graphene-django uses to return graphiql. It does look like it depends on static assets being available. 
https://github.com/graphql-python/graphene-django/blob/master/graphene_django/templates/graphene/graphiql.html

Maybe writing our own template using something like the graphiql cdn example would be better:
https://github.com/graphql/graphiql/blob/main/examples/graphiql-cdn/index.html

**Comment by znatty22** [comment]
I think the change that caused this to break happened in graphene-django 2.3: https://github.com/graphql-python/graphene-django/issues/685#issuecomment-580214353

**Comment by dankolbman** [comment]
I think we usually run with `DEBUG=True` and our browsers have the old bundle cached so it hasn't prevented us from using it in deploy environments.

**Comment by znatty22** [comment]
Ok I think I see what the (potential) issue is. Study creator is only able to load graphiql if you have `DEVELOP=True` because if you don't have that set to True, then the `Auth0AuthenticationMiddleware` logic is trying to execute and that seems to prevent the service from returning the graphiql interface. 

My question is, does `creator/settings/development.py` _need_ to have the `Auth0AuthenticationMiddleware` activated? If I comment it out, the graphiql interface comes up fine, but idk what else that would break. If it does need to be activated, then I would suggested adding something in the docs to state that you must have both `DEBUG=True` (as per graphene-django) and `DEVELOP=True` in order to use the graphiql interface

**Comment by dankolbman** [comment]
The end goal here is to be able to use it in production, too. We can't run with `DEBUG` on in production and we need Auth0 middleware, at least in production.
I'm not sure why the middleware would interfere with graphiql.

**Comment by znatty22** [comment]
Oh ok I didn't realize we also want it in production

**Comment by dankolbman** [comment]
I've added GraphiQL directly to our front end so this it's not necessary to serve it out of our api directly anymore.
